# Generated by Django 2.2.6 on 2020-03-30 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False, verbose_name='文件ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('tran_date', models.DateTimeField(verbose_name='收藏时间')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '已移出')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏列表',
            },
        ),
        migrations.CreateModel(
            name='Soltslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类别')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '分类列表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.CharField(max_length=30, null=True, verbose_name='邮箱')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '未知')], default=2, verbose_name='性别')),
                ('tran_date', models.DateTimeField(verbose_name='注册时间')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '禁用')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户列表',
            },
        ),
        migrations.CreateModel(
            name='Bookfile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False, verbose_name='文件ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('file_name', models.CharField(max_length=50, verbose_name='文件名')),
                ('md5_name', models.CharField(max_length=50, verbose_name='md5文件名')),
                ('tran_date', models.DateTimeField(verbose_name='上传时间')),
                ('status', models.IntegerField(choices=[(0, '共享'), (1, '私有')], default=0, verbose_name='状态')),
                ('solts', models.ForeignKey(db_column='name', null=True, on_delete=django.db.models.deletion.CASCADE, to='zbookapp.Soltslist', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件列表',
            },
        ),
    ]
